### PR TITLE
🐾 Voting refetching fixes

### LINKED ISSUE #2593: Refetch QN after reveal vote
## Context

Add button "Back to candidates" to reveal confirmation and when clicked, refetch qn to show updated progress on revealed candidate vote

https://www.loom.com/share/def23cc4a93e4bfd9c0f072c47a747ea

### LINKED ISSUE #2618: Refetch qn after voted
Context:

We need to extend the same approach as we did for #2593, to casting the vote. 

Actual result: Clicking on CTA in voting confirmation modal does not do anything
Expected result:
- [ ] Modal closes, 
- [ ] QN refetches and 
- [ ] My votes tab is shown with counter 
- My votes can always be visible, 
- No counter required for zero, 
- Show empty page placeholder copy for opened my votes tab. ⚠️ Use custom copy  "Your votes will be shown in this list. Single member can vote multiple times with different accounts." 

+
- [ ] I suggest to update CTA to "Back to Candidates" and keep the user on the same page (pun intended :P)

**References**

**Modal in question:**

**My openings empty state**
Screenshot 2022-03-22 at 18 38 16

### LINKED ISSUE #2638: Refetch QN after announce work entry
QN does not refetch after work entry announced Loom > https://www.loom.com/share/f5c650d061174aa8b8ff7eec39858886

Go to current bounties > must redirect and close the modal (now modal stays open)

### PR DESCRIPTION
**Pull request by RafalPloszka**
Closes #2618 
Closes #2638 
Closes #2593

Scope:
- [ ] everything from #2618
- [ ] closing modal from #2638
- [ ] button for modal from #2593

### CODE REVIEW

File: packages/ui/src/council/components/election/voting/VotingStage.tsx [hunk 1]
```diff
@@ -39,15 +40,21 @@ export const VotingStage = ({ election, isLoading }: VotingStageProps) => {
...
+        myVotes={votesTotal}
         tab={tab}
         onSetTab={(tab) => setTab(tab as VotingStageTab)}
       />
-      <CandidateCardList
-        candidates={tab === 'candidates' ? allCandidates : votedForCandidates}
-        isLoading={isLoading}
-        canVote={canVote}
-      />
+      {tab === 'myVotes' && !myVotes?.length ? (
```
Comment (stepien4soft) [inline packages/ui/src/council/components/election/voting/VotingStage.tsx:47]: just a suggestion: could you move it to const?

**Review by stepien4soft — APPROVED** [review]
