### PR TITLE
🧮 Update balances calculation

### LINKED ISSUE #720: The transferable balance is wrong
The current useBalance calculations are wrong.

It should be `total = transferable + locked` and right now transferable is the same as locked.

### PR DESCRIPTION
**Pull request by jodator**
Closes #720

### CODE REVIEW

File: packages/ui/src/accounts/model/toBalances.ts [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+  const { lockedBalance, availableBalance, lockedBreakdown, freeBalance } = balances
+
+  const locks = lockedBreakdown.map((lock) => ({
+    amount: lock.amount,
+    type: lockLookup(lock.id),
+  }))
+
+  const transferable = availableBalance.toBn()
+  const locked = lockedBalance.toBn()
+  const total = freeBalance.toBn() // Should be .add(reservedBalance) ?
```
Comment (DevNikita16) [inline packages/ui/src/accounts/model/toBalances.ts:23]: I think `const total = freeBalance.add(lockedBalance)` according to issue description

Comment (jodator) [reply packages/ui/src/accounts/model/toBalances.ts:23]: I've just found this comprehensive answer: [https://stackoverflow.com/a/56418101/2273046.](https://stackoverflow.com/a/56418101/2273046.) 

I'm still not 100% if Joystream will allow reserving a balance.

So,

*   total = free + reserved
*   transferable = free - locked (looks like duplicates `available`)
