### PR TITLE
🥴 Handle actions on success and canceled/failed post editing

### LINKED ISSUE #1465: Submitting the transaction should clear editing state
This might be tricky to implement, so a minimal requirement is to clear the editing state of a post right after the user hits "save".

The drawback is that user could close the transaction window in order to re-edit the data. This however, is a smaller issue than seeing this data still in the edit field.

### PR DESCRIPTION
**Pull request by DevNikita16**
See #1465

Alright, it was pretty hard to make perfect UX. 

I've come up with these solutions:
1) On success - we update text and time of post
2) On error or on canceling modal - we focus user back to inline editor. Previously it was looking really weird.

Regarding 2nd point - that was the big fight against react ref types. But it works nice as I think

### CODE REVIEW

File: packages/ui/src/forum/components/Thread/NewThreadPost.tsx [hunk 1]
```diff
@@ -50,7 +50,7 @@ export const NewThreadPost = React.forwardRef(
                 </Badge>
               </div>
               <div>
-                <ButtonPrimary size="small" onClick={removeReply}>
+                <ButtonPrimary size="small" square onClick={removeReply}>
```
Comment (DevNikita16) [inline packages/ui/src/forum/components/Thread/NewThreadPost.tsx:53]: This is out of PR scope. Just Vlad noticed that I need to add `square` here

**Comment by jodator** [comment]
> On error or on canceling modal - we focus user back to inline editor. Previously it was looking really weird.

:+1:

**Review by jodator — APPROVED** [review]
I didn't catch anything suspicious, so merging ;)
