### PR TITLE
Fix: issue 4485, check 4484

### LINKED ISSUE #4485: Forum: Category pages refreshing multiple times before loading
# Problem
Example: https://pioneerapp.xyz/#/forum/category/8

Page will load and refresh multiple times. This happens on different browsers and with or without wallet extension present.

### PR DESCRIPTION
**Pull request by mkbeefcake**
Fixed #4485 and  checked #4484

### CODE REVIEW

File: packages/ui/src/app/pages/Forum/ForumCategory.tsx [hunk 1]
```diff
@@ -48,17 +48,13 @@ export const ForumCategory = () => {
...
     interval: MILLISECONDS_PER_BLOCK,
     include: ['GetForumThreads', 'GetForumThreadsCount'],
   })
 
   const { showModal } = useModal()
 
-  if (isLoadingThreads && !isRefetched) {
-    return <Loading />
-  }
-
```
Comment (thesan) [inline packages/ui/src/app/pages/Forum/ForumCategory.tsx:61]: Great work on catching this ! It wasn't an easy one to debug :exploding_head: 

But I think the fix could be improved because first it now makes empty categories show a loader every 6 seconds e.g: https://dao-git-fork-mkbeefcake-fix-4485-4484-joystream.vercel.app/#/forum/category/17?network-config=https://34.230.5.182.nip.io/network/config.json. But more importantly it still refetch way to much data (as you pointed out on #4484). Also I realized we've struggled with this particular `useRefetch` for a long time (see #4318) so I really think the best is to remove this one.

Instead we could replace this logic by a `pollInterval` of 6 second in `packages/ui/src/forum/hooks/useForumCategoryThreads.ts` but only when `isArchive` is `false`. Also `isLoading` should become `!threadsData || !countData` this way `isLoading` is only `true` on the initial load.

**Review by thesan — CHANGES_REQUESTED** [review]

File: packages/ui/src/app/pages/Forum/ForumCategory.tsx (hunk 1 above)
Comment (mkbeefcake) [reply packages/ui/src/app/pages/Forum/ForumCategory.tsx:61]: image
Thanks for your guide. also I figured out "posts" field in forumThreads query, If i choose this mechanism, i can reduce the query count to 1, but it could take all posts info per each thread, so could take much data and a bit more loading time.
I hope to get your opinion about this.

Comment (thesan) [reply packages/ui/src/app/pages/Forum/ForumCategory.tsx:61]: Yes `forumThreads { posts { ... } }` will return all the posts for all the threads shown one the category page so I think 1 request per thread is a better trade off.

Comment (mkbeefcake) [reply packages/ui/src/app/pages/Forum/ForumCategory.tsx:61]: @thesan I have added posts field for ForumThread interface and fetched it in GetForumThreads Query, so reduce the queries in Forum Category page, please check the updated code.

File: packages/ui/src/forum/queries/forum.graphql [hunk 2]
```diff
@@ -122,6 +122,26 @@ fragment ForumThreadFields on ForumThread {
...
+      __typename
+    }
+    threadId
+    thread {
+      categoryId
+    }
+    author {
+      ...MemberFields
+    }
+  }
```
Comment (thesan) [inline packages/ui/src/forum/queries/forum.graphql:144]: I don't think we should go with this solution:
ATM on the Joystream General category it ~6x the size of the thread requests from `137kb` to `851kb` but the 30 posts request saved by this solution were between `4kb` to `10kb` so already the page queries a lot more data to start with. And then it repeats the thread request every 6 seconds. On top of that the thread request go all the way to several megabytes on some pages.

A bigger request can often be better than a lot of smaller one but here I really don't think this is worth it.

**Review by thesan — CHANGES_REQUESTED** [review]

File: packages/ui/src/forum/queries/forum.graphql (hunk 2 above)
Comment (mkbeefcake) [reply packages/ui/src/forum/queries/forum.graphql]: I have removed "posts" from thread and updated the code. please review and give me feedback
