### PR TITLE
👨‍🚀 Filter withdrawn applications from openings

### LINKED ISSUE #2833: [USERSNAP] Storage providers application page shows wrong information about applicants
## Scope

- [ ] Ensure QN is not returning 2 applicants
- [ ] Fix underlying problem in Pioneer

**Taken at**: https://dao.joystream.org/#/working-groups/openings/storageWorkingGroup-6
**Fields**:
- Houston, we have a problem.: Storage providers application page shows wrong information about applicants
- Comment: Each applicant should be displayed only once.

This screen shows user isonar twice. But CLI command shows only one application from user isonar:

```
Current Group: storageProviders


________________ Opening details _________________


 Opening ID                    6
 Opening type                  Regular
 Created                       #143716
 Reward per block              -


_________________ Staking policy _________________


 Stake amount                  52.0000 kJOY
 Unstaking period              43,200 blocks


____________________ Metadata ____________________


{
    description: null,
    shortDescription: null,
    hiringLimit: null,
    applicationDetails: null,
    applicationFormQuestions: [


    ]
}


________________ Applications (2) ________________


 ID     Member      Role Acc            Reward Acc          Staking Acc
 ────── ─────────── ─────────────────── ─────────────────── ───────────────────
 13     isonar      5HT8Mt...8XmjFy     5HT8Mt...8XmjFy     5Dr9aa...bp353H
 14     ppx2022     5HGfi1...gxEC6H     5Dc8ai...Bb89wa     5HGfi1...gxEC6H
```
- Not sure
- Feedback: singulart

SCREENSHOT
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/ee8dcb59-797b-4af2-bbc8-f3eddd160b2f-annotated_8fc53313-2ead-49f1-aafd-a7f5ddc38a4b.png?etag=73371ad7d23efe9e69de5f082259465c)*

**Browser**: Chrome 100 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1600x794
**[Open #194 in Usersnap](https://app.usersnap.com/l/feedback/38e2c73f-d27f-4da9-9a4b-63159c8ff9ec?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

### PR DESCRIPTION
**Pull request by freakstatic**
Fixes #2833

### CODE REVIEW

File: packages/ui/src/working-groups/components/ApplicantsList.tsx [hunk 1]
```diff
@@ -17,6 +17,8 @@ export interface WorkersListProps {
 }
 
 export const ApplicantsList = ({ hired, allApplicants, myApplication, hiringComplete, leadId }: WorkersListProps) => {
+  allApplicants = allApplicants?.filter((application) => application.status != 'ApplicationStatusWithdrawn')
```
Comment (WRadoslaw) [inline packages/ui/src/working-groups/components/ApplicantsList.tsx:20]:
```suggestion
  allApplicants = allApplicants?.filter((application) => application.status !== 'ApplicationStatusWithdrawn')
```

**Review by WRadoslaw — CHANGES_REQUESTED** [review]
Thanks for PR! Since @theo is overloaded I will try to cover this PR for him. 

I think it would be good to cover filtering out withdrawn applications in parent component of `ApplicantsList` under `useOpening`. The reason behind is that `myApplication` is currently resolved with `find` function on not filtered applications. In the example with isonar it may cause situation when it will find his withdrawn application first and display wrong application.  

Alternatively, instead of bringing filtering to parent, we can just add extra condition inside `find` for `myApplication`.

File: packages/ui/src/working-groups/components/ApplicantsList.tsx (hunk 1 above)
Comment (freakstatic) [reply packages/ui/src/working-groups/components/ApplicantsList.tsx]: > Thanks for PR! Since @theo is overloaded I will try to cover this PR for him.
> 
> I think it would be good to cover filtering out withdrawn applications in parent component of `ApplicantsList` under `useOpening`. The reason behind is that `myApplication` is currently resolved with `find` function on not filtered applications. In the example with isonar it may cause situation when it will find his withdrawn application first and display wrong application.
> 
> Alternatively, instead of bringing filtering to parent, we can just add extra condition inside `find` for `myApplication`.

Thanks for the review!
yeah well notice, I moved the filtering to the parent component, as you suggested, to avoid that problem

File: packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx [hunk 2]
```diff
@@ -44,6 +44,13 @@ export const WorkingGroupOpening = () => {
   const { showModal } = useModal()
   const { active: activeMembership } = useMyMemberships()
   const { isLoading, opening } = useOpening(id)
+
+  if (opening) {
+    opening.applications = opening.applications?.filter(
```
Comment (WRadoslaw) [inline packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx:49]: Last thing before merge. Please extract applications to `useMemo`, since filtering array is pretty heavy operation and number of applications hopefully will get pretty big in the future, we don't want do it with every re-render.

`const activeApplication = useMemo(() => .....)`

**Review by WRadoslaw — CHANGES_REQUESTED** [review]

File: packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx (hunk 2 above)
Comment (WRadoslaw) [reply packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx:49]: Sorry for not pointing it out at first approach

Comment (freakstatic) [reply packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx]: no problem!
I just committed the changes you suggested can you please check now?

**Review by WRadoslaw — APPROVED** [review]
