### PR TITLE
Fix WG opening route (#3399)

### LINKED ISSUE #3268: Wrong group names
## Scope
- [ ] The correct implementation was done in  [packages/ui/src/common/helpers.ts](https://github.com/Joystream/pioneer/blob/dev/packages/ui/src/common/helpers.ts#L25); function called `nameMapping`, we need to do the same in the other files

Expected result:
- more DRY code
- `operationsWorkingGroupBeta` resolves to "HR"
- `operationsWorkingGroupGamma` resolves to "Marketing"
- `#/working-groups/operationsWorkingGroupAlpha` re-routes to `#/working-groups/builders` (and analogues)

Supported routes:
- /#/working-groups/openings/apps-0
- /#/working-groups/openings/gatewayWorkingGroug-0 => `apps-0`
- /#/working-groups/openings/builders-0
- /#/working-groups/openings/operationsWorkingGroupAlpha-0 => re-routes to `builders-0`
- /#/working-groups/openings/hr-0
- /#/working-groups/openings/operationsWorkingGroupBeta-0 => `hr-0`
- /#/working-groups/openings/marketing-0
- /#/working-groups/openings/operationsWorkingGroupGamma-0 => `marketing-0`

## Context
Found 3 files where Marketing (Beta) and HR (Gamma) are swapped. Also note wrong Builders in `locks.ts`.

Looks like the error was introduced in https://github.com/Joystream/joystream/issues/3119
Corrected in https://github.com/Joystream/joystream/pull/3136#issuecomment-1033595381 (see [Sumer KPI: 38.III-1 New Working Groups](https://blog.joystream.org/sumer-kpis/#38.III-1))

https://github.com/Joystream/pioneer/blob/dev/packages/ui/src/working-groups/model/workingGroupName.ts
      case 'hr':
        return 'operationsWorkingGroupBeta'
      case 'marketing':
        return 'operationsWorkingGroupGamma'

https://github.com/Joystream/pioneer/blob/dev/packages/ui/src/common/helpers.ts#L44
case 'Operations Beta':
      return 'Human Resources working group is responsible for integrating new members greeting, onboarding, catalyzing and nurturing, as well as managing bounties.'
    case 'Operations Gamma':
      return 'Marketing group is responsible for increasing the outreach, sharing the content from the platform with the world, spreading the news about platform development, new members acquisition and overall growth.'

https://github.com/Joystream/pioneer/blob/dev/packages/ui/src/working-groups/types/locks.ts
  operationsWorkingGroupGamma: 'Builders Worker',
  operationsWorkingGroupBeta: 'HR Worker',
  operationsWorkingGroupAlpha: 'Marketing Worker',

### PR DESCRIPTION
**Pull request by traumschule**
see [#3399 ](https://github.com/Joystream/pioneer/pull/3399#issuecomment-1283548439) (fixes #3268)

### CODE REVIEW

**Comment by freakstatic** [comment]
thanks for taking care of this :+1:

File: packages/ui/src/working-groups/model/workingGroupName.ts [hunk 1]
```diff
@@ -20,3 +20,17 @@ export const urlParamToWorkingGroupId = (name: string) => {
 }
 
 export const groupNameToURLParam = (name: string) => name.toLowerCase().replace(/ /g, '-')
+
+/**
+ *
+ * @param name
+ *  name has this shape workingGroupName-runtimeId
+ * @returns
+ *  workingGroupId
```
Comment (WRadoslaw) [inline packages/ui/src/working-groups/model/workingGroupName.ts:29]: This function is pretty simple plus its naming explains its purpose pretty well, so I don't see a reason behind this documentation. 

Plus, doesn't it return something else?
```suggestion
 *  workingGroupId-openingRuntimeId
```

**Review by WRadoslaw — APPROVED** [review]

File: packages/ui/src/working-groups/model/workingGroupName.ts (hunk 1 above)
Comment (traumschule) [reply packages/ui/src/working-groups/model/workingGroupName.ts:29]: sorry, didn't even look at it. will add a commit to remove it.
