### PR TITLE
👁 Feature/loser withdraws stake

### LINKED ISSUE #2023: Worker Loser Withdraws Stake
- [ ] Loser can [Withdraw Stake](https://www.figma.com/file/jZwIoaxOkTxNFMJNzssBgv/Bounty?node-id=248%3A109434)

### LINKED ISSUE #2024: Entrant Withdraw Stake
Entrant can withdraw stake when Bounty Failed

AC
- [ ] [Withdraw stake link to Figma](https://www.figma.com/file/jZwIoaxOkTxNFMJNzssBgv/Bounty?node-id=248%3A109434)  
- [ ] Transaction Fee applies

ℹ️ 

[Link to Handbook](https://joystream.gitbook.io/joystream-handbook/subsystems/bounties#cancel-bounty)

### PR DESCRIPTION
**Pull request by stepien4soft**
closes #2023 closes #2024

### CODE REVIEW

File: packages/ui/src/bounty/modals/WithdrawalStakeModal/WithdrawStakeModal.tsx [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+    () => modalData.bounty.entries?.find((entry) => entry.worker.id === activeMember?.id),
+    [activeMember?.id]
+  )
+
+  const feeInfo = useTransactionFee(activeMember?.controllerAccount, transaction)
+
+  useEffect(() => {
+    if (state.matches(WithdrawalStakeStates.requirementsVerification)) {
+      if (transaction && feeInfo && activeMember) {
+        feeInfo.canAfford && send('NEXT')
```
Comment (WRadoslaw) [inline packages/ui/src/bounty/modals/WithdrawalStakeModal/WithdrawStakeModal.tsx:47]: `feeInfo.canAfford ? send('NEXT') : send('ERROR')` would be more straightforward, but it's only cosmetic

File: packages/ui/src/bounty/modals/WithdrawalStakeModal/WithdrawStakeModal.tsx [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+        !feeInfo.canAfford && send('ERROR')
+      }
+    }
+  }, [state.value, transaction, feeInfo?.canAfford])
+  if (state.matches(WithdrawalStakeStates.requirementsVerification)) {
+    return <WaitModal title="Please wait..." description={t('common:modals.wait.description')} onClose={hideModal} />
```
Comment (WRadoslaw) [inline packages/ui/src/bounty/modals/WithdrawalStakeModal/WithdrawStakeModal.tsx:53]: Missing translation

**Review by WRadoslaw — CHANGES_REQUESTED** [review]

**Review by WRadoslaw — APPROVED** [review]
