### PR TITLE
fixes #3968, fixes #4129 fix autoscroll to issue

### LINKED ISSUE #3968: Proposal discussion auto-scroll distraction
Triaging #3967 i noticed an auto-scroll behavior that keeps pulling back to the post every few seconds after clicking the 'replies to' link and scrolling further.

It should be fine to scroll only once.

### LINKED ISSUE #4129: [USERSNAP] Forum post auto-scrolling bug
**Taken at**: https://pioneerapp.xyz/#/proposals/preview/81?post=69
**Fields**:
- Houston, we have a problem.: Forum post auto-scrolling bug
- Comment: When I follow a link to a specific post, like https://pioneerapp.xyz/#/proposals/preview/81?post=69, then if I try to scroll to another part of the page I will be auto scrolled back to the post after a few seceonds.

SCREENSHOT
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/0f8b195b-3502-4893-9a24-4265c5e149be-annotated_8aff3c26-0b7f-4043-a40d-ddc523022ed8.png?etag=d102f9b1395b2f82df877f42c764d492)*

**Browser**: Firefox 109 (macOS Catalina)
**Screen size**: 5120x1440
**Browser size**: 1858x1171
**[Open #384 in Usersnap](https://app.usersnap.com/l/feedback/302c1b22-0355-47af-94c0-5ccbddfeb1c1?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

## Technical guidance:

The `` is happening [here](https://github.com/Joystream/pioneer/blob/0d308b26de798e8d41b8a7680b18b395ec42f03e/packages/ui/src/forum/components/PostList/PostListItem.tsx#L71):
```ts
useEffect(() => {
  if (ref.current && isSelected) {
    ref.current.scrollIntoView({ behavior: 'smooth', inline: 'start' })
  }
}, [location, ref.current])
```
I'm not 100% sure which of the 2 `useEffect` dependencies is at fault but I don't think `ref.current` should be here.

### PR DESCRIPTION
**Pull request by IlyaSmiyukha**
#3968 and #4129 same issue
@chrlschwb check pls

### CODE REVIEW

**Review by chrlschwb — APPROVED** [review]
ok

File: packages/ui/src/forum/components/PostList/PostListItem.tsx [hunk 1]
```diff
@@ -66,8 +67,9 @@ export const PostListItem = ({
   }, [ref.current])
 
   useEffect(() => {
-    if (ref.current && isSelected) {
+    if (ref.current && isSelected && firstLoad) {
       ref.current.scrollIntoView({ behavior: 'smooth', inline: 'start' })
+      setFirstLoad(false)
     }
   }, [location, ref.current])
```
Comment (thesan) [inline packages/ui/src/forum/components/PostList/PostListItem.tsx:74]: This solution would work but it add some unnecessary complexity.

Instead AFAICS both `location` and `ref.current` are the wrong dependencies `useEffect`.
1. `location` is actually the source of the problem because the `useLocation` hook returns a new JS object (same values different reference) on every rerender.
     Instead it should be:
    ```ts
    return useMemo(() => ({ pathname, search, hash, origin }), [pathname, search, hash])
    ```
     But in this case we should only care about `isSelected` (which itself depends on the location).

3. `ref.current` is assigned to the `ForumPostBlock` `div` before any of the `useEffect` get called, so it's useless to add it in the dependencies.
```suggestion
    if (ref.current && isSelected) {
      ref.current.scrollIntoView({ behavior: 'smooth', inline: 'start' })
    }
  }, [isSelected])
```
**Improtant:**
Please fix the `useLocation` hook (as described above) because it might cause unnecessary re-renders in other places and maybe some other bugs.

File: packages/ui/src/forum/components/PostList/PostListItem.tsx [hunk 2]
```diff
@@ -58,6 +58,7 @@ export const PostListItem = ({
   const { active } = useMyMemberships()
   const { createdAtBlock, lastEditedAt, author, text, repliesTo } = post
   const [postLastEditedAt, setPostLastEditedAt] = useState<string | undefined>(lastEditedAt)
+  const [firstLoad, setFirstLoad] = useState<boolean>(true)
   const location = useLocation()
```
Comment (thesan) [inline packages/ui/src/forum/components/PostList/PostListItem.tsx:62]:
```suggestion
```

**Review by thesan — CHANGES_REQUESTED** [review]

File: packages/ui/src/forum/components/PostList/PostListItem.tsx (hunk 1 above)
Comment (IlyaSmiyukha) [reply packages/ui/src/forum/components/PostList/PostListItem.tsx]: You right. Resolved

Comment (IlyaSmiyukha) [reply packages/ui/src/forum/components/PostList/PostListItem.tsx]: Done. Sorry misunderstood this part.

Comment (thesan) [reply packages/ui/src/forum/components/PostList/PostListItem.tsx]: Np!

**Review by thesan — APPROVED** [review]
:100: 

Thanks again !
