### PR TITLE
Multiple Constitutionality Proposal View Fix

### LINKED ISSUE #4111: Multiple constitutionality proposals display upd
## Context

At present proposals that need to undergo multiple constitutionality periods are displayed with multiple tabs. The future rounds of voting are disabled, while the last round is not represented in the tab. 

Here's an example: 

## Scope
- [ ] Display all voting periods in tabs all the time with future ones disabled.
In the example provided above, 3 rounds exists, so all of them need to be shown in tabs. 1/3; 2/3; 3/3

- [ ] Add tooltip on hover to the disabled tabs:
Tooltip copy: "This proposal must undergo the voting of multiple consequent councils. The result of each council vote will be displayed in the separate tabs. For the proposal to be approved, each of the councils must approve it." 

- [ ] Add info banner to the active / past rounds of voting.
"The number of councils in that must approve the proposal in a row before it has its intended effect is more than 1. The overall execution of proposal will be triggered after the last council completes the voting. Outcomes of each council voting is displayed in a separate tab."

### PR DESCRIPTION
**Pull request by chrlschwb**
fixes #4111, #4213, and #4201

### CODE REVIEW

File: packages/ui/src/proposals/hooks/useVotingRounds.ts [hunk 1]
```diff
@@ -28,7 +28,7 @@ export const useVotingRounds = (votes: ProposalVote[] = [], updates: ProposalSta
   const councilSize = useCouncilSize()
 
   const voteRounds: (Omit<VotingRound, 'count'> & { total?: number })[] = useMemo(() => {
-    const decidingCount = updates.filter(({ status }) => status === 'deciding').length || 1
+    const decidingCount = updates.findIndex(({ status }) => status === 'deciding') + 1 || 1
```
Comment (thesan) [inline packages/ui/src/proposals/hooks/useVotingRounds.ts:31]: I think this won't work.

To see how proposalStatusUpdates works check e.g:
```gql
{
  proposalByUniqueInput (where: { id: "63" }) {
    proposalStatusUpdates {
      newStatus { __typename }
    }
  }
}
```

You could use the index based on the assumption that only dormant and deciding stage alternate up to the last deciding stage. But that would be very unclear.

So I thinks this should be:
```suggestion
    const decidingCount = updates.filter(({ status }) => status === 'deciding').length + 1
```
Same as in `@/proposals/components/ProposalStages`

**Review by thesan — CHANGES_REQUESTED** [review]
Also please check the failing CI

File: packages/ui/src/proposals/hooks/useVotingRounds.ts (hunk 1 above)
Comment (chrlschwb) [reply packages/ui/src/proposals/hooks/useVotingRounds.ts:31]: If the suggested code is implemented, `decidingCount` will be 1 forever because there is only one update with the status `deciding` at any given time. 
As soon as a new deciding stage is entered, the former `deciding` stage goes into `dormant`.

File: packages/ui/src/proposals/components/ProposalHistory.tsx [hunk 2]
```diff
@@ -14,7 +14,7 @@ interface ProposalHistoryProps {
 export const ProposalHistory = ({ proposal }: ProposalHistoryProps) => {
   const history = useMemo((): StepperStep[] => {
     const updates = proposal.proposalStatusUpdates
-    const createdStatus = { status: 'Created', createdAt: proposal.createdAt, inBlock: proposal.createdInBlock }
+    const createdStatus = { status: 'Deciding', createdAt: proposal.createdAt, inBlock: proposal.createdInBlock }
```
[the remark this answers is not in the document]
Comment (chrlschwb) [reply packages/ui/src/proposals/components/ProposalHistory.tsx]: added a "Deciding" stage. 
The CI check is failing right after pulling from the "dev" branch. It is unrelated to this issue.

File: packages/ui/src/proposals/hooks/useVotingRounds.ts (hunk 1 above)
Comment (thesan) [reply packages/ui/src/proposals/hooks/useVotingRounds.ts:31]: No `update` keeps track of all stage changes.

Please try the query I wrote above on https://query.joystream.org/graphql

Because this proposal was voted on 3 times, it shows 2 `ProposalStatusDeciding` "newStatus" (as it doesn't include the initial deciding stage).

File: packages/ui/src/proposals/components/ProposalHistory.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (thesan) [reply packages/ui/src/proposals/components/ProposalHistory.tsx]: It looks related to me. The test suites failing are "useVotingRounds" and "ProposalPreview".

Check: https://github.com/Joystream/pioneer/actions/runs/4413195684/jobs/7733400617

**Review by thesan — APPROVED** [review]
