### PR TITLE
🚧 Fix bounty funding progressbar

### LINKED ISSUE #2655: Bounties: Refetch qn after contribution + contribution progress on bounty list card
Contribute Funds was no luck 🚫 tested on pioneer-2. Does this mean that was merged straight to prod (dao.joystream)?

https://www.loom.com/share/be6e0e0b32f941fdbdaeeff2247adcb8

update contribution progress bar on bounty list item / card

### PR DESCRIPTION
**Pull request by RafalPloszka**
Closes #2655

### CODE REVIEW

File: packages/ui/src/bounty/components/BountyListItem/components/FundingDetails.tsx [hunk 1]
```diff
@@ -20,7 +20,8 @@ export const FundingDetails = memo(({ fundingType, totalFunding, cherry }: Props
 
   if (!isFundingLimited(fundingType)) {
     const { target } = fundingType
-    const currentProgress = totalFunding.div(fundingType.target).toNumber()
+    // BN.js doesn't support decimals: https://github.com/indutny/bn.js/issues/213#issuecomment-475716946
+    const currentProgress = totalFunding.toNumber() / target.toNumber()
```
Comment (thesan) [inline packages/ui/src/bounty/components/BountyListItem/components/FundingDetails.tsx:24]: That makes sense but generally we should avoid converting these BNs into numbers directly.
This would give enough precision:
```suggestion
    const currentProgress = totalFunding.muln(100).div(target).toNumber() / 100
```

**Review by thesan — CHANGES_REQUESTED** [review]

**Review by thesan — APPROVED** [review]
