### PR TITLE
🤯 Bugfix/new statuses for bounties

### LINKED ISSUE #2275: Display Network and QN Ip address in the settings menu
### Context

Pioneer app can be pointed to a particular network endpoint (which also includes Query Node as part of the landscape).
To help testing and reporting bugs we need to surface the network in the UI. 

Current view of settings:
Screenshot 2022-02-21 at 08 48 37

### To-do
- [x] Add Network, Query Node and Faucet Server ip addresses to the settings page. 
- [x] Create tabs structure on the network page (to accommodate for future extension w Notifications mgt)

#### Designs

[Link to Figma](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8187%3A231780)

### LINKED ISSUE #2367: Change the Terminated status to either successful or failed for past bounties
For past bounties to distinguish between terminated success and terminated failure:

- [x] ~Change the Terminated status to either successful or failed for past bounties~ 
- [x] ~Display in the status bubble on bounties avatar image with statuses "successful"; "failed".~
> successful - in green shade of colour
> failed - in orange shade of colour
- [x] Reuse the same design of the bounty card which it was in before getting terminated 
- [x] In the drop down "periods" add three additional statuses: Terminated - successful; Terminated - failed; Terminated - from funding.
- [x] Add a white overlay over bounties background image (to display that this bounty is already "disabled" for interactions").
- [x] On terminated bounties detail page disable / hide the CTA for action (in the top right corner)

### PR DESCRIPTION
**Pull request by stepien4soft**
closes #2275 closes #2367

### CODE REVIEW

File: packages/ui/src/bounty/components/BountyListItem/BountyDetails.tsx [hunk 1]
```diff
@@ -62,7 +60,12 @@ export const BountyDetails = memo(
         case 'terminated': {
           return <TerminatedDetails entrants={entrants} />
         }
-        case 'withdrawal':
+        case 'successful': {
```
Comment (WRadoslaw) [inline packages/ui/src/bounty/components/BountyListItem/BountyDetails.tsx:65]: I guess you can use fall-through to improve code readability

**Review by WRadoslaw — APPROVED** [review]
