### PR TITLE
🧊 Fix entry stake value and validation

### LINKED ISSUE #2672: Wrong entrant stake value in the add entry modal
- [x] When the bounty entrant stake is set to e.g 200 the Announce Entry modal will still display 100 (which is currently the min entrant stake const).

- [x]  I'm not sure about the withdraw stake/reward modal.

### PR DESCRIPTION
**Pull request by RafalPloszka**
Closes #2672

### CODE REVIEW

**Review by thesan — CHANGES_REQUESTED** [review]
The problem is that the entrant stake is set on bounty creation (ATM there is no way to set a higher amount when announcing an entry). So this modal should only display the `bounty.entrantStake` value (so users know how much they're going to be staking as a result of the transaction)

File: packages/ui/src/bounty/modals/AnnounceWorkEntryModal/AnnounceWorkEntryModal.tsx [hunk 1]
```diff
@@ -52,21 +52,17 @@ export const AnnounceWorkEntryModal = () => {
     showModal,
   } = useModal<BountyAnnounceWorkEntryModalCall>()
   const { api, isConnected } = useApi()
-  const minWorkEntrantStake = api?.consts.bounty.minWorkEntrantStake.toNumber() ?? 0
   const { active: activeMember } = useMyMemberships()
   const { allAccounts } = useMyAccounts()
   const balances = useMyBalances()
-  const [amount, setAmount] = useState<string>(String(minWorkEntrantStake))
+  const minWorkEntrantStake = bounty.entrantStake
+  const [amount, setAmount] = useState<string>(minWorkEntrantStake.toString())
```
Comment (thesan) [inline packages/ui/src/bounty/modals/AnnounceWorkEntryModal/AnnounceWorkEntryModal.tsx:59]:
```suggestion
  const amount = bounty.entrantStake
```
I think this `amount` should also replace `contribution`

Comment (RafalPloszka) [reply packages/ui/src/bounty/modals/AnnounceWorkEntryModal/AnnounceWorkEntryModal.tsx:59]: `Amount` is string and `contribution` is BN (as required for components it is passed to), so this 'conversion' is needed, but we can get rid of useMemo, as it won't change, do you agree?

**Review by thesan — APPROVED** [review]
