### PR TITLE
💥 Add modal for failed balance check

### LINKED ISSUE #198: Insufficient funds check for Transfer Invites modal
@[figma](https://www.figma.com/file/J2KUqGu97lNQC2iKsxJeVH/My-Profile?node-id=192%3A17548)

### Requirements

- Validate transaction fees before creating modal
- Display modal with information.

### PR DESCRIPTION
**Pull request by p-sad**
Closes #198

### CODE REVIEW

File: packages/ui/src/components/TransferButton.tsx [hunk 1]
```diff
@@ -14,33 +14,38 @@ interface Props {
 }
 
 export function TransferButton({ from, to, disabled }: Props) {
-  const [isOpen, toggleOpen] = useToggle()
+  const { showModal } = useModal()
   const isTransfer = !from && !to
   const isSend = !!from && !isTransfer
-  const icon = isTransfer ? <TransferIcon /> : isSend ? <ArrowOutsideIcon /> : <ArrowInsideIcon />
+  const iconName: TransferIconName = isTransfer ? 'TransferIcon' : isSend ? 'SendIcon' : 'ReceiveIcon'
```
Comment (jodator) [inline packages/ui/src/components/TransferButton.tsx:20]: Let's extract this logic to have:

```
type TransferType: 'Send' | 'Receive' | 'Transfer'
const getType( from: boolean, to: boolan ) => TransferType
```

Having this we don't have to push `icon` to the modal and we can have the same component that renders different icons depending on the type.

```
<TransferIcon type={getIconType(true, false)} />
```

Another thing is to update the button accordingly.

**Review by jodator — CHANGES_REQUESTED** [review]
The modal looks superb :) After reading the code I came to mind that we don't have to push this icon in the data.
Let's change that.

**Review by jodator — APPROVED** [review]
