### PR TITLE
🗳️ Fix past votes stake recovering

### LINKED ISSUE #2834: [USERSNAP] My Profile" `Recover` opens past-votes for Vote Stakes
### Scope

- [ ] Hide recover lock button for the duration of election cycle if candidate lost, and for duration of election+council normal round if candidate won.

In simple words we want the same logic for recovering the lock is the same as we did on profile page.
________________
**Taken at**: https://dao.joystream.org/#/profile
**Fields**:
- Houston, we have a problem.: My Profile&#34; `Recover` opens past-votes for Vote Stakes
- Comment: It should in fact open route https://dao.joystream.org/#/election/past-votes where recovering actually works.
- For **Vote Stakes** the recover button on https://dao.joystream.org/#/profile does nothing except collapsing account details (and hiding the button).
- Feedback: l1dev

SCREENSHOT
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/f4605450-8ac7-41d9-a4cb-f0283096f6a9-annotated_3ca36767-8a50-4bd1-877b-e25d63a34dd5.png?etag=1b0379ad5392d27ddab35206650510e3)*

**Browser**: Chrome 99 (Linux)
**Screen size**: 1920x1080
**Browser size**: 2868x1460
**[Open #195 in Usersnap](https://app.usersnap.com/l/feedback/e400d060-0a9f-48c3-88af-d39e23488e82?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

### PR DESCRIPTION
**Pull request by RafalPloszka**
Closes #2834

### CODE REVIEW

**Comment by RafalPloszka** [comment]
:warning: Important note: This PR also fixes hardcoded `isCouncilMember: false` (by using a hook instead) in #2363

File: packages/ui/src/accounts/hooks/useIsVoteStakeLocked.ts [hunk 1]
```diff
@@ -0,0 +1,14 @@
+import { useMemo } from 'react'
+
+import { LatestElection } from '@/council/types/LatestElection'
+import { useIsCouncilMember } from '@/memberships/hooks/useIsCouncilMember'
+import { Member } from '@/memberships/types'
+
+export const useIsVoteStakeLocked = (latestElection?: LatestElection, candidate?: Member) => {
+  const isCouncilMember = useIsCouncilMember(candidate)
```
Comment (thesan) [inline packages/ui/src/accounts/hooks/useIsVoteStakeLocked.ts:8]: Since #1536 was closed I think there's no need for this hook anymore. The `false` in `@/memberships/types/casting.ts` should just be replaced by `data.isCouncilMember` and `useIsCouncilMember` should be remove (I should have done this in #1990 though :facepalm:)

**Review by thesan — CHANGES_REQUESTED** [review]

File: packages/ui/src/accounts/hooks/useIsVoteStakeLocked.ts [hunk 2]
```diff
@@ -0,0 +1,12 @@
...
+import { Member } from '@/memberships/types'
+
+export const useIsVoteStakeLocked = (candidate?: Member, electionFinished?: boolean) => {
+  const isCouncilMember = candidate?.isCouncilMember
+  return useMemo(() => {
+    // Lock stake if the vote was cast: in current election or to winning candidate
+    // Enable stake recovery if election is finished
+    return !!candidate && (!electionFinished || isCouncilMember)
+  }, [electionFinished, candidate])
+}
```
Comment (thesan) [inline packages/ui/src/accounts/hooks/useIsVoteStakeLocked.ts:12]: It's better now but it's still missing the case where a member which was candidate in a previous election (not the latest one) is now a council member. This is why I suggested `isLatestElection`. I'm thinking of something like this:

```suggestion
// Lock stake if the vote was cast: in current election or to winning candidate
// Enable stake recovery if election is finished
export const useIsVoteStakeLocked = (candidate?: Member, { isElectionFinished = true, isLatestElection = true }) =>
  isLatestElection && !!candidate && (!isElectionFinished || candidate.isCouncilMember)
```

File: packages/ui/src/council/components/PastVotes/PastVote/PastVote.tsx [hunk 3]
```diff
@@ -36,7 +38,10 @@ export const PastVote = ({ vote, $colLayout }: PastVoteProps) => {
     })
   }
 
-  const isDisabled = !vote.stakeLocked || isTransactionPending
+  const isVoteStakeLocked = useIsVoteStakeLocked(vote.voteFor, false)
```
Comment (thesan) [inline packages/ui/src/council/components/PastVotes/PastVote/PastVote.tsx:41]: The election should be finished here
```suggestion
  const isVoteStakeLocked = useIsVoteStakeLocked(vote.voteFor, true)
```

File: packages/ui/src/council/components/PastVotes/PastVotesList.tsx [hunk 4]
```diff
@@ -9,6 +9,7 @@ import { RowGapBlock } from '@/common/components/page/PageContent'
 import { Pagination } from '@/common/components/Pagination'
 import { NotFoundText } from '@/common/components/typography/NotFoundText'
 import { useSort } from '@/common/hooks/useSort'
+import { useLatestElection } from '@/council/hooks/useLatestElection'
```
Comment (thesan) [inline packages/ui/src/council/components/PastVotes/PastVotesList.tsx:12]: This is not used now
```suggestion
```

**Review by thesan — CHANGES_REQUESTED** [review]
I'm really sorry about the long review delay on this.

In addition to the other comments please:
1. To have this work: uncomment the `isCouncilMember` and `data.isCouncilMember` in `@/memberships/queries/members.graphql` (and remove the `# See https://github.com/Joystream/pioneer/issues/1536`) and `@/memberships/types/casting`
2. This is a bit off topic but as a result of (1): Remove the `useCouncilMember` hook and replace each time it's called by e.g `member.isCouncilMember`

**Review by thesan — APPROVED** [review]
Looks good, thanks for fixing extra stuff in this PR. And also cutting it in small commits that really helped me :raised_hands:
