### PR TITLE
Fix/filter lead

### LINKED ISSUE #3704: lead appears twice in workers list
Task: Filter workers for non-leads.

lead-twice
builders

### PR DESCRIPTION
**Pull request by traumschule**
fixes #3704

broke [test/app/pages/WorkingGroup.test.tsx](https://github.com/Joystream/pioneer/actions/runs/3317806331/jobs/5481053207#step:7:475)

### CODE REVIEW

File: packages/ui/src/working-groups/components/WorkersList.tsx [hunk 1]
```diff
@@ -28,7 +28,12 @@ export const WorkersList = ({ lead, workers }: WorkersListProps) => {
         {workers && (
           <ContentWithTabs>
             {workers.map((worker, index) => (
```
Comment (WRadoslaw) [inline packages/ui/src/working-groups/components/WorkersList.tsx:30]: Isn't it easier to just not render anything when the worker is a lead? Especially that `isLead` sounds like this component will render smth extra when the worker is a leader, not just omit it.

```suggestion
            {workers.map((worker, index) => worker.member.id !== lead?.meber.id && (
```
or just filter the results

```suggestion
            {workers.filter(worker => worker.member.id !== lead?.member.id).map((worker, index) => (
```

**Review by WRadoslaw — CHANGES_REQUESTED** [review]

**Review by WRadoslaw — APPROVED** [review]

**Comment by traumschule** [comment]
Shall i create a followup for the broken tests? Not sure how to fix the [timeout](https://github.com/Joystream/pioneer/actions/runs/3317806331/jobs/5481053207#step:7:636) on the fly.

**Comment by oleksanderkorn** [comment]
> Shall i create a followup for the broken tests? Not sure how to fix the [timeout](https://github.com/Joystream/pioneer/actions/runs/3317806331/jobs/5481053207#step:7:636) on the fly.

Restarting tests usually helps, this looks like a flaky test. I had it before on my branches multiple times.
